### ISSUE TITLE
Exclude directories?

### ISSUE THREAD

**Issue by k4y4k** [Destaq/language-statistics#3]
Hey there :wave: 

First off: this is pretty epic ngl. Works flawlessly, 9.99/10.

However, when I ran this inside my [Vue 3 and TypeScript] project folder, I was instead presented with:
![output](https://user-images.githubusercontent.com/41324271/113552263-3fa4cf80-9639-11eb-89cd-93c7f7f195cf.png)

Removing `node_modules` (i.e. where the project's dependencies are installed) gives me something closer to what I'd expected (because why would I be writing AppleScript??! What the heck is an OCaml??!!!): 
![output](https://user-images.githubusercontent.com/41324271/113552387-6f53d780-9639-11eb-9301-0322a4f6a9c8.png)

Thus, I'm here to ask: is there an argument or some kind of config I can pass in to exclude certain directories? I didn't see anything in the README.

Edit: to be clear, I'm aware I can just slap a "NAH, BYE, IGNORE" on stuff like EJS and whatnot that I know I'm not writing, but I'm specifically looking to run this from the root of my project (and thus can't siphon off things like CSS, which are present in `node_modules` as well as the project's `src/`.

Cheers!
  kayak

**Comment by Destaq** [comment]
Hi, from the docs you can exclude *language extensions* but unfortunately not directories.

> -e or --exclude: which file extensions to exclude when searching for files and creating the image. These files will be ignored and will not affect the total percentage or show up. You can specify multiple. Example: statistics -e .ipynb .css .HTML

I can see how this would be a useful feature, however. A few lines of code should be able to resolve the problem by filtering out directories in [this function](https://github.com/Destaq/language-statistics/blob/d18ece02aadda5cda6c02e594cba2fd012de6357/language_statistics/language_bytes.py#L139); free to open a pull request to address the issue. If not, I can set it up but am somewhat busy at the moment so may take several days.

**Comment by k4y4k** [comment]
No wakkas. If I manage to get something together I'll open a PR :v:

**Comment by Destaq** [comment]
It's been a year but I finally got around to it!

**Comment by k4y4k** [comment]
oh my god it has been a year 😆 thank you!!
